### ISSUE TITLE
Navigation in ReactiveReader sample is broken

### ISSUE THREAD

**Issue by macqm** [reactiveui/samples#10]
I tried compiling your samples and they run, however the navigation don't seem to work at all. FeedsView is never created. This branch is never executed, and I thought it should have been (App.xaml.cs @ line 69):

            if (shell.Content == null)
            {
                // When the navigation stack isn't restored navigate to the first page,
                // configuring the new page by passing required information as a navigation
                // parameter
                shell.AppFrame.Navigate(typeof(FeedsViewModel), e.Arguments);
            }

**Comment by NPadrutt** [comment]
That's true. The example is not nearly finished. The existing navigation didn't work with the idea to make the sample also cover Android. But you're right, I have to continue here.

**Comment by macqm** [comment]
Where did Android come from? I was compiling it for Win 10 (UWP). 

I tried:

    if (shell.AppFrame.Content == null)
    {
         // When the navigation stack isn't restored navigate to the first page,
         // configuring the new page by passing required information as a navigation
         // parameter
         shell.AppFrame.Navigate(typeof(FeedsViewModel), e.Arguments);
    }

just like in the [official sample](https://github.com/Microsoft/Windows-universal-samples/blob/93bdfb92b3da76f2e49c959807fc5643bf0940c9/Samples/XamlNavigation/cs/App.xaml.cs#L78-L83), but that throws a `NullRefrenceException`. The Navigate method expects a Type of a page, not a view model type. Can you explain how it should work?

**Comment by NPadrutt** [comment]
The Android project has yet to come. But the point is, that if you want to support Android you currently can't use view model based navigation.
So in this example you would need to use:

    shell.AppFrame.Navigate(typeof(FeedsView), e.Arguments);

Otherwise if you only want to support UWP, you can use the ViewModel based navigation. This would need you to do some changes on the AppShell. I assume you would have to bind a comman and on the selection changed do the navigation in the viewmodel.

**Comment by macqm** [comment]
I don't want to target Android - I don't know what made you assume this. I was trying to build your sample for UWP and it seems to use ViewModel based navigation and it doesn't work.

**Comment by NPadrutt** [comment]
Just tried to explain why it has the current state =)
I guess an important point is that you're code snipped AFAIKViewModelBased isn't routing. Unfortunately I can't give you a proper example right now. Only have used the view based navigation so far.
maybe @ghuntley can help you with that.

**Comment by NPadrutt** [comment]
I had a look at the code again and saw some issues who might be a part of your confusion. #11
But still. If you want just to target UWP this example probably isn't what you're looking for.

**Comment by macqm** [comment]
I am afraid I am not sure that I understand:
> I guess an important point is that you're code snipped AFAIKViewModelBased isn't routing


Moreover, if this sample isn't for UWP (then what is it for? Android? I lost you again), can you please make it clear in README.md?

**Comment by ghuntley** [comment]
Easy there @macqm

ReactiveReader is a view first implementation of ReactiveUI for all supported platforms. At this stage UWP is partially implemented and @NPadrutt volunteered in his spare time to help evolve the code-base to UWP and Android.

Apologies for the confusion, I should not have published it on the main branch until it was ready for consumption and as such I've unpublished it.

If your looking at using RxUI with UWP you should come introduce yourself in Slack https://github.com/reactiveui/reactiveui#slack. Right now the focus is being up the community there and as knowledge is passed down via the campfire it is being documented.

Regards,
Geoff

**Comment by macqm** [comment]
Thanks for this explanation @ghuntley, I didn't mean to sound arrogant. I do appreciate the work you and @NPadrutt  put in these samples and I'd love to help to get the sample to work on UWP and learn what 'view first' means in this context, thanks for the pointer to Slack.

**Comment by ghuntley** [comment]
Water under the bridge @macqm, we would love to [have you as our neighbor](https://www.youtube.com/watch?v=Vtc7A67kZlQ) and hope to see you in Slack shortly. If the invitation process doesn't work then bump this thread and I'll follow up with Paul.

* ViewFirst means navigation is done at the view level on each platform ie. `AppContentFrame.Navigate(typeof (TView));`
* ViewModel means navigation is done at the viewmodel level and you'll end up implementing a ViewModelHost within your AppShell which hands the switching Pages in/out.

ViewModel based navigation is the ultimate as you can unit test the navigation easily and single implementation on all platforms. The problem is all platforms have different navigation patterns so to handle this type of concern an abstraction (presenter) is needed. RxUI is currently lacking a good xplat presentation story https://github.com/reactiveui/ReactiveUI/issues/1048 so if you will be targeting multiple platforms you should go ViewFirst or pitchin and help with 1048 :-)
